apiVersion: v1
kind: Service
metadata:
  name: ejbsamplegradle
  labels:
    app: ejbsamplegradle
    app.kubernetes.io/component: ejbsamplegradle
spec:
  selector:
    app: ejbsamplegradle
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
